### ISSUE TITLE
3.14.5 import WebDavException fails

### ISSUE THREAD

**Issue by JOJ0** [ezhov-evgeny/webdav-client-python-3#71]
Hi,
it seems with version 3.14.5, I can't import WebDavException anymore. It worked with 3.14.4.
Anything changed in this area?
Thanks!

```
Traceback (most recent call last):
  File "/Users/jojo/.venvs/discodos/bin/discosync", line 6, in <module>
    from discodos.cmd.sync import main
  File "/Users/jojo/git/discodos/discodos/cmd/sync.py", line 21, in <module>
    from webdav3.client import WebDavException
ImportError: cannot import name 'WebDavException' from 'webdav3.client' (/Users/jojo/.venvs/discodos/lib/python3.7/site-packages/webdav3/client.py)
```

**Comment by ezhov-evgeny** [comment]
@JOJ0 Yes, please use import of all exceptions from `webdav3.exceptions`.

**Comment by JOJ0** [comment]
Hi,
thanks for the quick answer! Perfect, working now! Thanks for a great module btw! And just so you know: I am currently packaging it for Debian Linux as package named python3-webdavclient because my software [DiscoDOS](https://github.com/JOJ0/discodos) uses it for backing up its database. If all goes well your module will be in Debian unstable in a couple of weeks and on it's way into the Debian/Ubuntu universe. Hope you like that! I will try to keep maintaining the Debian package, update it whenever I find the time :-)

I have another question about webdavclient3 too but I think I'll open another issue for that.
all the best
Jojo

**Comment by ezhov-evgeny** [comment]
Thank you for feedback. I am glad to know the library is useful.
Good luck with your project! Please share the link to package for Debian when it will be ready.
